name: "publish"
on:
  release:
    types: [created]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: "install"
        run: npm install
      - name: "create package"
        run: npm run package
      - name: "publish"
        run: npm publish ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}